# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:tffire/TestPrivateSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
 
end
